import { createHmac, timingSafeEqual } from "node:crypto"

/**
 * Verifies Meta's `X-Hub-Signature-256` header against the raw request body.
 *
 * Meta signs every webhook delivery with the app secret. Without checking it,
 * the endpoint accepts anything anyone posts to it -- and what it would accept
 * is "this customer just messaged us", which is precisely the fact the seller
 * uses to decide whether the chat is open. A forged event would tell them to
 * start adding products to a chat that will reject every one.
 *
 * The comparison is constant-time. Lengths are compared first because
 * `timingSafeEqual` throws on a length mismatch rather than returning false,
 * which would turn a malformed header into a 500 instead of a rejection.
 */
export function signatureMatches(
  rawBody: string,
  header: string | null,
  secret: string | undefined
): boolean {
  // No secret configured means the endpoint cannot prove anything about who is
  // calling it, so it refuses rather than trusting the body. Failing closed is
  // the point: a webhook left open is an open write endpoint.
  if (!secret || !header) return false

  const expected = "sha256=" + createHmac("sha256", secret).update(rawBody, "utf8").digest("hex")
  const received = Buffer.from(header, "utf8")
  const computed = Buffer.from(expected, "utf8")
  if (received.length !== computed.length) return false
  return timingSafeEqual(received, computed)
}

export interface InboundMessage {
  /** The customer's number in WhatsApp's own format: digits, no `+`. */
  from: string
  /** Meta's message id, unique per message. */
  id: string
  /** When the customer sent it. */
  sentAt: Date
  type: string
  text?: string
}

/**
 * Pulls the customer messages out of a webhook payload.
 *
 * Meta nests them four levels deep and mixes them with delivery receipts and
 * status updates, which must not be mistaken for a message: a `sent` or `read`
 * receipt is generated by our own outbound message and would otherwise look
 * like the customer writing to us, holding the window open forever in the UI
 * while Meta considers it shut.
 *
 * Anything unrecognised is skipped rather than thrown on. This payload comes
 * from outside and its shape changes with Graph versions, so a new field must
 * never take the endpoint down.
 */
export function inboundMessages(payload: unknown): InboundMessage[] {
  const messages: InboundMessage[] = []
  if (!isRecord(payload)) return messages

  for (const entry of asArray(payload.entry)) {
    if (!isRecord(entry)) continue
    for (const change of asArray(entry.changes)) {
      if (!isRecord(change)) continue
      const value = isRecord(change.value) ? change.value : null
      if (!value) continue
      for (const message of asArray(value.messages)) {
        if (!isRecord(message)) continue
        const from = typeof message.from === "string" ? message.from : null
        const id = typeof message.id === "string" ? message.id : null
        if (!from || !id) continue

        // Meta sends the timestamp as seconds, as a string.
        const seconds = Number(message.timestamp)
        const sentAt = Number.isFinite(seconds) && seconds > 0
          ? new Date(seconds * 1000)
          : new Date()

        const text = isRecord(message.text) && typeof message.text.body === "string"
          ? message.text.body
          : undefined

        messages.push({
          from,
          id,
          sentAt,
          type: typeof message.type === "string" ? message.type : "unknown",
          text,
        })
      }
    }
  }
  return messages
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function asArray(value: unknown): unknown[] {
  return Array.isArray(value) ? value : []
}
