import { createHmac } from "node:crypto"
import { describe, expect, it } from "vitest"
import { inboundMessages, signatureMatches } from "@/lib/whatsapp/signature"

const SECRET = "app_secret_for_tests"

function sign(body: string, secret = SECRET): string {
  return "sha256=" + createHmac("sha256", secret).update(body, "utf8").digest("hex")
}

describe("webhook signature", () => {
  it("accepts a body Meta signed with the app secret", () => {
    const body = '{"object":"whatsapp_business_account"}'
    expect(signatureMatches(body, sign(body), SECRET)).toBe(true)
  })

  it("rejects a body that was altered after signing", () => {
    const body = '{"object":"whatsapp_business_account"}'
    const header = sign(body)
    expect(signatureMatches(body + " ", header, SECRET)).toBe(false)
  })

  it("rejects a signature made with a different secret", () => {
    const body = '{"a":1}'
    expect(signatureMatches(body, sign(body, "someone_elses_secret"), SECRET)).toBe(false)
  })

  // Failing closed is the point: an unsigned webhook is an open write endpoint,
  // and what it would accept is "the customer messaged us" -- the one fact the
  // seller uses to decide whether the chat is open.
  it("rejects everything when no secret is configured", () => {
    const body = '{"a":1}'
    expect(signatureMatches(body, sign(body), undefined)).toBe(false)
    expect(signatureMatches(body, sign(body), "")).toBe(false)
  })

  it("rejects a missing or malformed header without throwing", () => {
    const body = '{"a":1}'
    expect(signatureMatches(body, null, SECRET)).toBe(false)
    expect(signatureMatches(body, "", SECRET)).toBe(false)
    expect(signatureMatches(body, "sha256=short", SECRET)).toBe(false)
    expect(signatureMatches(body, "not-a-signature-at-all", SECRET)).toBe(false)
  })
})

describe("inbound messages", () => {
  const textMessage = {
    object: "whatsapp_business_account",
    entry: [{
      id: "WABA_ID",
      changes: [{
        field: "messages",
        value: {
          messaging_product: "whatsapp",
          metadata: { display_phone_number: "15556498481", phone_number_id: "PNID" },
          contacts: [{ profile: { name: "Camila R." }, wa_id: "573001234567" }],
          messages: [{
            from: "573001234567",
            id: "wamid.HBgMNTczMDAx",
            timestamp: "1789000000",
            type: "text",
            text: { body: "Hola Brash3D, confirmo mi sesión" },
          }],
        },
      }],
    }],
  }

  it("reads a customer's text message", () => {
    const [message] = inboundMessages(textMessage)
    expect(message.from).toBe("573001234567")
    expect(message.id).toBe("wamid.HBgMNTczMDAx")
    expect(message.type).toBe("text")
    expect(message.text).toBe("Hola Brash3D, confirmo mi sesión")
    // Meta sends seconds, as a string.
    expect(message.sentAt.getTime()).toBe(1789000000 * 1000)
  })

  /*
   * A `sent`/`delivered`/`read` receipt is generated by our own outbound
   * message. Counting one as an inbound message would hold the window open in
   * the UI forever while Meta considers it shut -- the seller would be told to
   * keep adding products to a chat rejecting every one of them.
   */
  it("ignores delivery and read receipts", () => {
    const statuses = {
      object: "whatsapp_business_account",
      entry: [{
        id: "WABA_ID",
        changes: [{
          field: "messages",
          value: {
            messaging_product: "whatsapp",
            metadata: { phone_number_id: "PNID" },
            statuses: [{
              id: "wamid.OUTBOUND",
              status: "read",
              timestamp: "1789000100",
              recipient_id: "573001234567",
            }],
          },
        }],
      }],
    }
    expect(inboundMessages(statuses)).toHaveLength(0)
  })

  it("reads a non-text message without a body", () => {
    const image = structuredClone(textMessage)
    image.entry[0].changes[0].value.messages[0] = {
      from: "573001234567",
      id: "wamid.IMAGE",
      timestamp: "1789000200",
      type: "image",
    } as (typeof image.entry)[0]["changes"][0]["value"]["messages"][0]

    const [message] = inboundMessages(image)
    expect(message.type).toBe("image")
    expect(message.text).toBeUndefined()
  })

  it("reads every message when several arrive in one delivery", () => {
    const batched = structuredClone(textMessage)
    batched.entry[0].changes[0].value.messages.push({
      from: "573009999999",
      id: "wamid.SECOND",
      timestamp: "1789000300",
      type: "text",
      text: { body: "Segunda" },
    })
    expect(inboundMessages(batched).map((m) => m.id)).toEqual(["wamid.HBgMNTczMDAx", "wamid.SECOND"])
  })

  // The payload comes from outside and its shape moves with Graph versions, so
  // an unexpected field must never take the endpoint down.
  it("returns nothing for payloads it does not recognise, rather than throwing", () => {
    for (const payload of [null, undefined, 42, "text", [], {}, { entry: null }, { entry: [{}] },
      { entry: [{ changes: [{ value: {} }] }] },
      { entry: [{ changes: [{ value: { messages: [{ id: "no-from" }] } }] }] }]) {
      expect(inboundMessages(payload)).toEqual([])
    }
  })
})
